# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3dc791ddc9e5fe3a9ce1c8c7b08e500f73815523a22a59f5018a44670c8955b772d01063d78683fc06e354de504824680d582173f7f2f5db06b738714df6b85

test:
  secret_key_base: 7454d4f59e3417bc21bc606d22fd9d2965c56e59d37a538f18cb7786df1f711740d67f55f7bca9cbe877a5ce8a60839744217a35557e3ca68cc43de24cfa0c59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
